<?php
/**
 * @property CI_DB_query_builder $db
 * @property CI_DB_forge $dbforge
 * @property CI_Benchmark $benchmark
 * @property CI_Calendar $calendar
 * @property CI_Cart $cart
 * @property CI_Config $config
 * @property CI_Email $email
 * @property CI_Encrypt $encrypt
 * @property CI_Exceptions $exceptions
 * @property CI_Form_validation $form_validation
 * @property CI_Ftp $ftp
 * @property CI_Hooks $hooks
 * @property CI_Image_lib $image_lib
 * @property CI_Input $input
 * @property CI_Lang $lang
 * @property CI_Loader $load
 * @property CI_Log $log
 * @property CI_Model $model
 * @property CI_Output $output
 * @property CI_Pagination $pagination
 * @property CI_Parser $parser
 * @property CI_Profiler $profiler
 * @property CI_Session $session
 * @property CI_Security $security
 * @property CI_URI $uri
 * @property CI_User_agent $agent
 * @property CI_Xmlrpc $xmlrpc
 * @property CI_Xmlrpcs $xmlrpcs
 * @property CI_Zip $zip
 *
 * // Models automáticamente generados basados en tu lista
 * @property Activity_logs_model $activity_logs_model
 * @property Agreements_evidences_model $agreements_evidences_model
 * @property Agreements_matrix_config_model $agreements_matrix_config_model
 * @property Agreements_monitoring_model $agreements_monitoring_model
 * @property Agreements_rel_fields_model $agreements_rel_fields_model
 * @property Air_files_model $air_files_model
 * @property Air_models_model $air_models_model
 * @property Air_records_model $air_records_model
 * @property Air_records_types_model $air_records_types_model
 * @property Air_records_values_p_max_model $air_records_values_p_max_model
 * @property Air_records_values_p_min_model $air_records_values_p_min_model
 * @property Air_records_values_p_model $air_records_values_p_model
 * @property Air_records_values_p_porc_conf_model $air_records_values_p_porc_conf_model
 * @property Air_records_values_uploads_model $air_records_values_uploads_model
 * @property Air_sectors_model $air_sectors_model
 * @property Air_stations_model $air_stations_model
 * @property Air_stations_rel_variables_model $air_stations_rel_variables_model
 * @property Air_stations_values_1h_model $air_stations_values_1h_model
 * @property Air_stations_values_1m_model $air_stations_values_1m_model
 * @property Air_stations_values_5m_model $air_stations_values_5m_model
 * @property Air_stations_values_15m_model $air_stations_values_15m_model
 * @property Air_synoptic_data_model $air_synoptic_data_model
 * @property Air_variables_model $air_variables_model
 * @property Air_variables_types_model $air_variables_types_model
 * @property Announcements_model $announcements_model
 * @property Api_model $api_model
 * @property Assignment_combinations_model $assignment_combinations_model
 * @property Assignment_model $assignment_model
 * @property Attendance_model $attendance_model
 * @property AYN_Admin_modules_model $ayn_admin_modules_model
 * @property AYN_Admin_submodules_model $ayn_admin_submodules_model
 * @property AYN_Alert_historical_air_model $ayn_alert_historical_air_model
 * @property AYN_Alert_historical_model $ayn_alert_historical_model
 * @property AYN_Alert_historical_users_model $ayn_alert_historical_users_model
 * @property AYN_Alert_projects_groups_model $ayn_alert_projects_groups_model
 * @property AYN_Alert_projects_model $ayn_alert_projects_model
 * @property AYN_Alert_projects_users_model $ayn_alert_projects_users_model
 * @property AYN_Clients_groups_model $ayn_clients_groups_model
 * @property AYN_Notif_general_groups_model $ayn_notif_general_groups_model
 * @property AYN_Notif_general_model $ayn_notif_general_model
 * @property AYN_Notif_general_users_model $ayn_notif_general_users_model
 * @property AYN_Notif_historical_model $ayn_notif_historical_model
 * @property AYN_Notif_historical_users_model $ayn_notif_historical_users_model
 * @property AYN_Notif_projects_admin_groups_model $ayn_notif_projects_admin_groups_model
 * @property AYN_Notif_projects_admin_model $ayn_notif_projects_admin_model
 * @property AYN_Notif_projects_admin_users_model $ayn_notif_projects_admin_users_model
 * @property AYN_Notif_projects_clients_groups_model $ayn_notif_projects_clients_groups_model
 * @property AYN_Notif_projects_clients_model $ayn_notif_projects_clients_model
 * @property AYN_Notif_projects_clients_users_model $ayn_notif_projects_clients_users_model
 * @property Calculation_model $calculation_model
 * @property Categories_alias_model $categories_alias_model
 * @property Categories_model $categories_model
 * @property Characterization_factors_model $characterization_factors_model
 * @property Client_compromises_settings_model $client_compromises_settings_model
 * @property Client_consumptions_settings_model $client_consumptions_settings_model
 * @property Client_context_modules_model $client_context_modules_model
 * @property Client_context_modules_rel_profiles_model $client_context_modules_rel_profiles_model
 * @property Client_context_profiles_model $client_context_profiles_model
 * @property Client_context_submodules_model $client_context_submodules_model
 * @property Client_environmental_footprints_settings_model $client_environmental_footprints_settings_model
 * @property Client_indicators_model $client_indicators_model
 * @property Client_module_availability_model $client_module_availability_model
 * @property Client_permitting_settings_model $client_permitting_settings_model
 * @property Client_waste_settings_model $client_waste_settings_model
 * @property Clients_model $clients_model
 * @property Clients_modules_model $clients_modules_model
 * @property Clients_modules_rel_profiles_model $clients_modules_rel_profiles_model
 * @property Clients_submodules_model $clients_submodules_model
 * @property Communities_evaluation_status_model $communities_evaluation_status_model
 * @property Compromises_compliance_evaluation_rca_model $compromises_compliance_evaluation_rca_model
 * @property Compromises_compliance_evaluation_reportables_model $compromises_compliance_evaluation_reportables_model
 * @property Compromises_compliance_evidences_model $compromises_compliance_evidences_model
 * @property Compromises_compliance_status_model $compromises_compliance_status_model
 * @property Compromises_rca_model $compromises_rca_model
 * @property Compromises_rca_rel_fields_model $compromises_rca_rel_fields_model
 * @property Compromises_reportables_model $compromises_reportables_model
 * @property Compromises_reportables_rel_fields_model $compromises_reportables_rel_fields_model
 * @property Contact_model $contact_model
 * @property Conversion_model $conversion_model
 * @property Countries_model $countries_model
 * @property Critical_levels_model $critical_levels_model
 * @property Crud_bd_fc_model $crud_bd_fc_model
 * @property Crud_model $crud_model
 * @property Custom_field_values_model $custom_field_values_model
 * @property Custom_fields_model $custom_fields_model
 * @property Databases_model $databases_model
 * @property EC_Client_transformation_factors_config_model $ec_client_transformation_factors_config_model
 * @property EC_Types_no_apply_model $ec_types_no_apply_model
 * @property EC_Types_of_origin_matter_model $ec_types_of_origin_matter_model
 * @property EC_Types_of_origin_model $ec_types_of_origin_model
 * @property Email_templates_model $email_templates_model
 * @property Environmental_records_model $environmental_records_model
 * @property Estimate_forms_model $estimate_forms_model
 * @property Estimate_items_model $estimate_items_model
 * @property Estimate_requests_model $estimate_requests_model
 * @property Estimates_model $estimates_model
 * @property Evaluated_permitting_model $evaluated_permitting_model
 * @property Evaluated_rca_compromises_model $evaluated_rca_compromises_model
 * @property Events_model $events_model
 * @property Expense_categories_model $expense_categories_model
 * @property Expenses_model $expenses_model
 * @property Fairs_model $fairs_model
 * @property Faq_model $faq_model
 * @property Feedback_matrix_config_model $feedback_matrix_config_model
 * @property Feedback_monitoring_evidences_model $feedback_monitoring_evidences_model
 * @property Feedback_monitoring_model $feedback_monitoring_model
 * @property Feedback_rel_fields_model $feedback_rel_fields_model
 * @property Feeders_model $feeders_model
 * @property FH_rel_methodology_model $fh_rel_methodology_model
 * @property Field_rel_form_model $field_rel_form_model
 * @property Field_types_model $field_types_model
 * @property Fields_model $fields_model
 * @property Fixed_field_rel_form_rel_project_model $fixed_field_rel_form_rel_project_model
 * @property Fixed_fields_model $fixed_fields_model
 * @property Fixed_form_values_model $fixed_form_values_model
 * @property Fontawesome_model $fontawesome_model
 * @property Footprint_format_model $footprint_format_model
 * @property Footprints_model $footprints_model
 * @property Form_rel_material_model $form_rel_material_model
 * @property Form_rel_materiales_rel_categorias_model $form_rel_materiales_rel_categorias_model
 * @property Form_rel_project_model $form_rel_project_model
 * @property Form_types_model $form_types_model
 * @property Form_values_model $form_values_model
 * @property Forms_model $forms_model
 * @property Functional_units_model $functional_units_model
 * @property General_files_model $general_files_model
 * @property General_settings_clients_model $general_settings_clients_model
 * @property General_settings_model $general_settings_model
 * @property Help_articles_model $help_articles_model
 * @property Help_categories_model $help_categories_model
 * @property Home_modules_info_model $home_modules_info_model
 * @property Indicators_model $indicators_model
 * @property Industries_model $industries_model
 * @property Industries_rel_technologies_model $industries_rel_technologies_model
 * @property Invoice_items_model $invoice_items_model
 * @property Invoice_payments_model $invoice_payments_model
 * @property Invoices_model $invoices_model
 * @property Items_model $items_model
 * @property KPI_Charts_structure_model $kpi_charts_structure_model
 * @property KPI_Report_structure_model $kpi_report_structure_model
 * @property KPI_Report_templates_model $kpi_report_templates_model
 * @property KPI_Values_condition_model $kpi_values_condition_model
 * @property KPI_Values_model $kpi_values_model
 * @property Leave_applications_model $leave_applications_model
 * @property Leave_types_model $leave_types_model
 * @property Logs_model $logs_model
 * @property Materials_model $materials_model
 * @property Materials_rel_category_model $materials_rel_category_model
 * @property Messages_model $messages_model
 * @property Methodology_model $methodology_model
 * @property Methodology_rel_footprints_model $methodology_rel_footprints_model
 * @property Milestones_model $milestones_model
 * @property Mimasoft_model $mimasoft_model
 * @property Module_availability_model $module_availability_model
 * @property Module_footprint_units_model $module_footprint_units_model
 * @property Notes_model $notes_model
 * @property Notification_settings_model $notification_settings_model
 * @property Notifications_model $notifications_model
 * @property Ods_model $ods_model
 * @property Other_records_model $other_records_model
 * @property Payment_methods_model $payment_methods_model
 * @property Paypal_ipn_model $paypal_ipn_model
 * @property Permitting_model $permitting_model
 * @property Permitting_procedure_evaluation_model $permitting_procedure_evaluation_model
 * @property Permitting_procedure_evidences_model $permitting_procedure_evidences_model
 * @property Permitting_procedure_status_model $permitting_procedure_status_model
 * @property Permitting_rel_fields_model $permitting_rel_fields_model
 * @property Phase_rel_pu_model $phase_rel_pu_model
 * @property Phases_model $phases_model
 * @property Plans_reportables_compromises_model $plans_reportables_compromises_model
 * @property Posts_model $posts_model
 * @property Profiles_model $profiles_model
 * @property Project_comments_model $project_comments_model
 * @property Project_files_model $project_files_model
 * @property Project_members_model $project_members_model
 * @property Project_rel_activities_model $project_rel_activities_model
 * @property Project_rel_footprints_model $project_rel_footprints_model
 * @property Project_rel_material_model $project_rel_material_model
 * @property Project_rel_phases_model $project_rel_phases_model
 * @property Project_rel_pu_model $project
 * @property Project_rel_pu_model $project_rel_pu_model
 * @property Project_settings_model $project_settings_model
 * @property Projects_model $projects_model
 * @property Reports_configuration_model $reports_configuration_model
 * @property Reports_model $reports_model
 * @property Reports_units_settings_clients_model $reports_units_settings_clients_model
 * @property Reports_units_settings_model $reports_units_settings_model
 * @property Roles_model $roles_model
 * @property Rule_model $rule_model
 * @property Settings_model $settings_model
 * @property Social_links_model $social_links_model
 * @property Stakeholders_matrix_config_model $stakeholders_matrix_config_model
 * @property Stakeholders_rel_fields_model $stakeholders_rel_fields_model
 * @property Subcategories_model $subcategories_model
 * @property Subcategory_rel_categories_model $subcategory_rel_categories_model
 * @property Subindustries_model $subindustries_model
 * @property Subprojects_model $subprojects_model
 * @property Tasks_model $tasks_model
 * @property Taxes_model $taxes_model
 * @property Team_model $team_model
 * @property Technologies_model $technologies_model
 * @property Thresholds_model $thresholds_model
 * @property Ticket_comments_model $ticket_comments_model
 * @property Ticket_types_model $ticket_types_model
 * @property Tickets_model $tickets_model
 * @property Timesheets_model $timesheets_model
 * @property Tipo_tratamiento_model $tipo_tratamiento_model
 * @property Todo_model $todo_model
 * @property Types_of_organization_model $types_of_organization_model
 * @property Unit_processes_model $unit_processes_model
 * @property Unity_model $unity_model
 * @property Unity_type_model $unity_type_model
 * @property Users_model $users_model
 * @property Values_agreements_model $values_agreements_model
 * @property Values_compromises_rca_model $values_compromises_rca_model
 * @property Values_compromises_reportables_model $values_compromises_reportables_model
 * @property Values_feedback_model $values_feedback_model
 * @property Values_model $values_model
 * @property Values_permitting_model $values_permitting_model
 * @property Values_stakeholders_model $values_stakeholders_model
 * @property Wiki_model $wiki_model
 */
class CI_Controller {

}
?>