services:
  nginx:
    build:
      context: ../..
      dockerfile: docker/prod-centinela/nginx/Dockerfile
    container_name: nginx-container-centinela
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/sites-available/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - php-fpm
    networks:
      - app-network
    cap_add:
      - NET_ADMIN
    privileged: true

  php-fpm:
    build:
      context: ../..
      dockerfile: docker/prod-centinela/Dockerfile
    volumes:
      - ../../app:/var/www/html
    container_name: php-fpm-centinela
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      - app-network

  db:
    build:
      context: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql-centinela
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

    networks:
      - app-network


volumes:
  db_data:
networks:
  app-network:
    driver: bridge